name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # On cible une version récente de Dart pour profiter des nouvelles features

dependencies:
  flutter:
    sdk: flutter
  
  # --- UI & Utilitaires ---
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  uuid: ^4.2.1
  
  # --- Réseau & Données ---
  http: ^1.1.0
  shared_preferences: ^2.2.2 # Version stable récente
  
  # --- Partage (Remplacement de flutter_share) ---
  share_plus: ^7.2.1 # Plus maintenu et compatible que flutter_share
  
  # --- Logging (Pour remplacer les print) ---
  logger: ^2.0.0 # Permet des logs structurés avec niveaux (debug, error, info)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Pour forcer les bonnes pratiques de code

flutter:
  uses-material-design: true
  assets:
    - assets/rules/
    - assets/data/
    - assets/images/tiles/